"""Add next_difficulty field to interview_sessions

Revision ID: c6ecad687cbd
Revises: bf1e37acf0a7
Create Date: 2025-09-02 23:09:06.137235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6ecad687cbd'
down_revision = 'bf1e37acf0a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('next_difficulty', sa.String(length=50), nullable=True))
    op.alter_column('interview_sessions', 'performance_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('interview_sessions', 'difficulty_level',
               existing_type=mysql.ENUM('easy', 'medium', 'hard', 'expert'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('interview_sessions', 'session_mode',
               existing_type=mysql.ENUM('new', 'practice_again', 'continued'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'new'"))
    op.drop_index(op.f('idx_interview_sessions_difficulty_level'), table_name='interview_sessions')
    op.drop_index(op.f('idx_interview_sessions_parent_session'), table_name='interview_sessions')
    op.drop_index(op.f('idx_interview_sessions_performance_score'), table_name='interview_sessions')
    op.drop_index(op.f('idx_interview_sessions_session_mode'), table_name='interview_sessions')
    op.drop_index(op.f('idx_interview_sessions_user_status_date'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_active_user_performance'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_completed_at'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_completed_with_metrics'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_difficulty'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_performance_analysis'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_recent_performance'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_role_performance'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_session_continuity'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_status_created'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_target_role'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_user_created'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_user_status'), table_name='interview_sessions')
    op.drop_index(op.f('idx_sessions_user_status_date_optimized'), table_name='interview_sessions')
    op.drop_index(op.f('idx_user_session_performance_trend'), table_name='interview_sessions')
    op.alter_column('learning_resources', 'category',
               existing_type=mysql.ENUM('body_language', 'voice_analysis', 'content_quality', 'overall'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('learning_resources', 'type',
               existing_type=mysql.ENUM('video', 'course'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('learning_resources', 'level',
               existing_type=mysql.ENUM('beginner', 'intermediate', 'advanced'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('learning_resources', 'ranking_weight',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'1.00'"))
    op.drop_index(op.f('idx_category_level_type'), table_name='learning_resources')
    op.drop_index(op.f('idx_learning_resources_category_level'), table_name='learning_resources')
    op.drop_index(op.f('idx_learning_resources_ranking_weight'), table_name='learning_resources')
    op.drop_index(op.f('idx_learning_resources_type_provider'), table_name='learning_resources')
    op.drop_index(op.f('idx_resources_category_level'), table_name='learning_resources')
    op.drop_index(op.f('idx_resources_provider_ranking'), table_name='learning_resources')
    op.drop_index(op.f('idx_resources_ranking'), table_name='learning_resources')
    op.drop_index(op.f('idx_resources_recommendation_lookup'), table_name='learning_resources')
    op.drop_index(op.f('idx_resources_type_level'), table_name='learning_resources')
    op.create_index(op.f('ix_learning_resources_id'), 'learning_resources', ['id'], unique=False)
    op.drop_index(op.f('idx_password_resets_cleanup'), table_name='password_resets')
    op.drop_index(op.f('idx_password_resets_expires'), table_name='password_resets')
    op.drop_index(op.f('idx_password_resets_security'), table_name='password_resets')
    op.drop_index(op.f('idx_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('idx_password_resets_used'), table_name='password_resets')
    op.drop_index(op.f('idx_password_resets_user_expires'), table_name='password_resets')
    op.drop_index(op.f('idx_password_resets_user_used'), table_name='password_resets')
    op.drop_index(op.f('idx_metrics_aggregation_optimized'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_body_score'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_comprehensive_scores'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_content_score'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_question_performance'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_response_time_analysis'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_session_analysis_optimized'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_session_created'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_session_question'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_tone_score'), table_name='performance_metrics')
    op.drop_index(op.f('idx_performance_metrics_response_time'), table_name='performance_metrics')
    op.drop_index(op.f('idx_performance_metrics_scores_composite'), table_name='performance_metrics')
    op.drop_index(op.f('idx_performance_metrics_session_created'), table_name='performance_metrics')
    op.drop_index(op.f('idx_questions_created_at'), table_name='questions')
    op.drop_index(op.f('idx_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('idx_questions_generated_by'), table_name='questions')
    op.drop_index(op.f('idx_questions_generation_lookup'), table_name='questions')
    op.drop_index(op.f('idx_questions_role_difficulty'), table_name='questions')
    op.drop_index(op.f('idx_questions_role_difficulty_type'), table_name='questions')
    op.drop_index(op.f('idx_questions_type_generated'), table_name='questions')
    op.drop_index(op.f('idx_questions_type_role'), table_name='questions')
    op.alter_column('role_hierarchy', 'sub_role',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('role_hierarchy', 'version',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'1.0'"))
    op.drop_index(op.f('idx_main_sub'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_active'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_complete_lookup'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_main'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_main_sub_active'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_specialization'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_sub'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_role_hierarchy_tech_stack'), table_name='role_hierarchy')
    op.drop_index(op.f('idx_version_active'), table_name='role_hierarchy')
    op.create_index(op.f('ix_role_hierarchy_id'), 'role_hierarchy', ['id'], unique=False)
    op.drop_index(op.f('idx_progress_comprehensive_tracking'), table_name='user_progress')
    op.drop_index(op.f('idx_progress_metric_score'), table_name='user_progress')
    op.drop_index(op.f('idx_progress_recommendations_lookup'), table_name='user_progress')
    op.drop_index(op.f('idx_progress_trend_analysis'), table_name='user_progress')
    op.drop_index(op.f('idx_progress_user_date'), table_name='user_progress')
    op.drop_index(op.f('idx_progress_user_metric'), table_name='user_progress')
    op.drop_index(op.f('idx_progress_user_metric_date_optimized'), table_name='user_progress')
    op.drop_index(op.f('idx_user_progress_metric_type'), table_name='user_progress')
    op.drop_index(op.f('idx_user_progress_user_date'), table_name='user_progress')
    op.alter_column('user_recommendations', 'user_feedback',
               existing_type=mysql.ENUM('liked', 'disliked', 'neutral'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'neutral'"))
    op.drop_index(op.f('idx_recommendations_clicked'), table_name='user_recommendations')
    op.drop_index(op.f('idx_recommendations_feedback'), table_name='user_recommendations')
    op.drop_index(op.f('idx_recommendations_user_recommended'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_recommendations_analytics'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_recommendations_clicked'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_recommendations_engagement'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_recommendations_feedback'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_recommendations_user_recommended'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_recommendations_user_resource'), table_name='user_recommendations')
    op.drop_index(op.f('idx_user_resource'), table_name='user_recommendations')
    op.create_index(op.f('ix_user_recommendations_id'), 'user_recommendations', ['id'], unique=False)
    op.drop_index(op.f('idx_user_sessions_cleanup'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_expires'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_security'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('idx_user_sessions_user_expires'), table_name='user_sessions')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_created_updated'), table_name='users')
    op.drop_index(op.f('idx_users_email_active'), table_name='users')
    op.drop_index(op.f('idx_users_email_active_optimized'), table_name='users')
    op.drop_index(op.f('idx_users_last_login'), table_name='users')
    op.drop_index(op.f('idx_users_last_login_active'), table_name='users')
    op.drop_index(op.f('idx_users_main_role'), table_name='users')
    op.drop_index(op.f('idx_users_role_active'), table_name='users')
    op.drop_index(op.f('idx_users_role_hierarchy_composite'), table_name='users')
    op.drop_index(op.f('idx_users_role_hierarchy_lookup'), table_name='users')
    op.drop_index(op.f('idx_users_specialization'), table_name='users')
    op.drop_index(op.f('idx_users_sub_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_sub_role'), 'users', ['sub_role'], unique=False)
    op.create_index(op.f('idx_users_specialization'), 'users', ['specialization'], unique=False)
    op.create_index(op.f('idx_users_role_hierarchy_lookup'), 'users', ['main_role', 'sub_role', 'specialization', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_role_hierarchy_composite'), 'users', ['main_role', 'sub_role', 'specialization'], unique=False)
    op.create_index(op.f('idx_users_role_active'), 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_main_role'), 'users', ['main_role'], unique=False)
    op.create_index(op.f('idx_users_last_login_active'), 'users', ['last_login', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('idx_users_email_active_optimized'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_email_active'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_created_updated'), 'users', ['created_at', 'updated_at'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_user_sessions_user_expires'), 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('idx_user_sessions_token'), 'user_sessions', ['session_token'], unique=False)
    op.create_index(op.f('idx_user_sessions_security'), 'user_sessions', ['user_id', 'ip_address', 'created_at'], unique=False)
    op.create_index(op.f('idx_user_sessions_expires'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('idx_user_sessions_cleanup'), 'user_sessions', ['expires_at', 'created_at'], unique=False)
    op.drop_index(op.f('ix_user_recommendations_id'), table_name='user_recommendations')
    op.create_index(op.f('idx_user_resource'), 'user_recommendations', ['user_id', 'resource_id'], unique=False)
    op.create_index(op.f('idx_user_recommendations_user_resource'), 'user_recommendations', ['user_id', 'resource_id'], unique=False)
    op.create_index(op.f('idx_user_recommendations_user_recommended'), 'user_recommendations', ['user_id', 'recommended_at'], unique=False)
    op.create_index(op.f('idx_user_recommendations_feedback'), 'user_recommendations', ['user_feedback'], unique=False)
    op.create_index(op.f('idx_user_recommendations_engagement'), 'user_recommendations', ['resource_id', 'clicked', 'user_feedback', 'recommended_at'], unique=False)
    op.create_index(op.f('idx_user_recommendations_clicked'), 'user_recommendations', ['clicked'], unique=False)
    op.create_index(op.f('idx_user_recommendations_analytics'), 'user_recommendations', ['user_id', 'recommended_at', 'clicked', 'user_feedback'], unique=False)
    op.create_index(op.f('idx_recommendations_user_recommended'), 'user_recommendations', ['user_id', 'recommended_at'], unique=False)
    op.create_index(op.f('idx_recommendations_feedback'), 'user_recommendations', ['user_feedback'], unique=False)
    op.create_index(op.f('idx_recommendations_clicked'), 'user_recommendations', ['clicked'], unique=False)
    op.alter_column('user_recommendations', 'user_feedback',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('liked', 'disliked', 'neutral'),
               existing_nullable=True,
               existing_server_default=sa.text("'neutral'"))
    op.create_index(op.f('idx_user_progress_user_date'), 'user_progress', ['user_id', 'session_date'], unique=False)
    op.create_index(op.f('idx_user_progress_metric_type'), 'user_progress', ['metric_type'], unique=False)
    op.create_index(op.f('idx_progress_user_metric_date_optimized'), 'user_progress', ['user_id', 'metric_type', 'session_date'], unique=False)
    op.create_index(op.f('idx_progress_user_metric'), 'user_progress', ['user_id', 'metric_type'], unique=False)
    op.create_index(op.f('idx_progress_user_date'), 'user_progress', ['user_id', 'session_date'], unique=False)
    op.create_index(op.f('idx_progress_trend_analysis'), 'user_progress', ['user_id', 'session_date', 'score', 'improvement_trend'], unique=False)
    op.create_index(op.f('idx_progress_recommendations_lookup'), 'user_progress', ['user_id'], unique=False)
    op.create_index(op.f('idx_progress_metric_score'), 'user_progress', ['metric_type', 'score'], unique=False)
    op.create_index(op.f('idx_progress_comprehensive_tracking'), 'user_progress', ['user_id', 'metric_type', 'session_date', 'score', 'improvement_trend'], unique=False)
    op.drop_index(op.f('ix_role_hierarchy_id'), table_name='role_hierarchy')
    op.create_index(op.f('idx_version_active'), 'role_hierarchy', ['version', 'is_active'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_tech_stack'), 'role_hierarchy', ['main_role', 'sub_role'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_sub'), 'role_hierarchy', ['sub_role'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_specialization'), 'role_hierarchy', ['specialization'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_main_sub_active'), 'role_hierarchy', ['main_role', 'sub_role', 'is_active'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_main'), 'role_hierarchy', ['main_role'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_complete_lookup'), 'role_hierarchy', ['main_role', 'sub_role', 'specialization', 'is_active', 'version'], unique=False)
    op.create_index(op.f('idx_role_hierarchy_active'), 'role_hierarchy', ['is_active'], unique=False)
    op.create_index(op.f('idx_main_sub'), 'role_hierarchy', ['main_role', 'sub_role'], unique=False)
    op.alter_column('role_hierarchy', 'version',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'1.0'"))
    op.alter_column('role_hierarchy', 'sub_role',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('idx_questions_type_role'), 'questions', ['question_type', 'role_category'], unique=False)
    op.create_index(op.f('idx_questions_type_generated'), 'questions', ['question_type', 'generated_by'], unique=False)
    op.create_index(op.f('idx_questions_role_difficulty_type'), 'questions', ['role_category', 'difficulty_level', 'question_type'], unique=False)
    op.create_index(op.f('idx_questions_role_difficulty'), 'questions', ['role_category', 'difficulty_level'], unique=False)
    op.create_index(op.f('idx_questions_generation_lookup'), 'questions', ['generated_by', 'created_at', 'difficulty_level'], unique=False)
    op.create_index(op.f('idx_questions_generated_by'), 'questions', ['generated_by'], unique=False)
    op.create_index(op.f('idx_questions_difficulty'), 'questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('idx_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('idx_performance_metrics_session_created'), 'performance_metrics', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_performance_metrics_scores_composite'), 'performance_metrics', ['content_quality_score', 'body_language_score', 'tone_confidence_score'], unique=False)
    op.create_index(op.f('idx_performance_metrics_response_time'), 'performance_metrics', ['response_time'], unique=False)
    op.create_index(op.f('idx_metrics_tone_score'), 'performance_metrics', ['tone_confidence_score'], unique=False)
    op.create_index(op.f('idx_metrics_session_question'), 'performance_metrics', ['session_id', 'question_id'], unique=False)
    op.create_index(op.f('idx_metrics_session_created'), 'performance_metrics', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_metrics_session_analysis_optimized'), 'performance_metrics', ['session_id', 'created_at', 'content_quality_score'], unique=False)
    op.create_index(op.f('idx_metrics_response_time_analysis'), 'performance_metrics', ['response_time', 'content_quality_score'], unique=False)
    op.create_index(op.f('idx_metrics_question_performance'), 'performance_metrics', ['question_id', 'content_quality_score', 'created_at'], unique=False)
    op.create_index(op.f('idx_metrics_content_score'), 'performance_metrics', ['content_quality_score'], unique=False)
    op.create_index(op.f('idx_metrics_comprehensive_scores'), 'performance_metrics', ['session_id', 'content_quality_score', 'body_language_score', 'tone_confidence_score'], unique=False)
    op.create_index(op.f('idx_metrics_body_score'), 'performance_metrics', ['body_language_score'], unique=False)
    op.create_index(op.f('idx_metrics_aggregation_optimized'), 'performance_metrics', ['session_id', 'question_id', 'content_quality_score', 'body_language_score', 'tone_confidence_score', 'created_at'], unique=False)
    op.create_index(op.f('idx_password_resets_user_used'), 'password_resets', ['user_id', 'used'], unique=False)
    op.create_index(op.f('idx_password_resets_user_expires'), 'password_resets', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('idx_password_resets_used'), 'password_resets', ['used'], unique=False)
    op.create_index(op.f('idx_password_resets_token'), 'password_resets', ['token'], unique=False)
    op.create_index(op.f('idx_password_resets_security'), 'password_resets', ['user_id', 'used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_password_resets_expires'), 'password_resets', ['expires_at'], unique=False)
    op.create_index(op.f('idx_password_resets_cleanup'), 'password_resets', ['expires_at', 'used'], unique=False)
    op.drop_index(op.f('ix_learning_resources_id'), table_name='learning_resources')
    op.create_index(op.f('idx_resources_type_level'), 'learning_resources', ['type', 'level'], unique=False)
    op.create_index(op.f('idx_resources_recommendation_lookup'), 'learning_resources', ['category', 'level', 'ranking_weight', 'type'], unique=False)
    op.create_index(op.f('idx_resources_ranking'), 'learning_resources', ['ranking_weight'], unique=False)
    op.create_index(op.f('idx_resources_provider_ranking'), 'learning_resources', ['provider', 'ranking_weight', 'category'], unique=False)
    op.create_index(op.f('idx_resources_category_level'), 'learning_resources', ['category', 'level'], unique=False)
    op.create_index(op.f('idx_learning_resources_type_provider'), 'learning_resources', ['type', 'provider'], unique=False)
    op.create_index(op.f('idx_learning_resources_ranking_weight'), 'learning_resources', ['ranking_weight'], unique=False)
    op.create_index(op.f('idx_learning_resources_category_level'), 'learning_resources', ['category', 'level'], unique=False)
    op.create_index(op.f('idx_category_level_type'), 'learning_resources', ['category', 'level', 'type'], unique=False)
    op.alter_column('learning_resources', 'ranking_weight',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'1.00'"))
    op.alter_column('learning_resources', 'level',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('beginner', 'intermediate', 'advanced'),
               existing_nullable=False)
    op.alter_column('learning_resources', 'type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('video', 'course'),
               existing_nullable=False)
    op.alter_column('learning_resources', 'category',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('body_language', 'voice_analysis', 'content_quality', 'overall'),
               existing_nullable=False)
    op.create_index(op.f('idx_user_session_performance_trend'), 'interview_sessions', ['user_id', 'created_at', 'performance_score', 'difficulty_level', 'target_role'], unique=False)
    op.create_index(op.f('idx_sessions_user_status_date_optimized'), 'interview_sessions', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('idx_sessions_user_status'), 'interview_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_sessions_user_created'), 'interview_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_sessions_target_role'), 'interview_sessions', ['target_role'], unique=False)
    op.create_index(op.f('idx_sessions_status_created'), 'interview_sessions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_sessions_session_continuity'), 'interview_sessions', ['parent_session_id', 'session_mode', 'created_at'], unique=False)
    op.create_index(op.f('idx_sessions_role_performance'), 'interview_sessions', ['target_role', 'performance_score', 'status'], unique=False)
    op.create_index(op.f('idx_sessions_recent_performance'), 'interview_sessions', ['user_id', 'performance_score', 'difficulty_level'], unique=False)
    op.create_index(op.f('idx_sessions_performance_analysis'), 'interview_sessions', ['user_id', 'performance_score', 'difficulty_level', 'created_at'], unique=False)
    op.create_index(op.f('idx_sessions_difficulty'), 'interview_sessions', ['difficulty_level'], unique=False)
    op.create_index(op.f('idx_sessions_completed_with_metrics'), 'interview_sessions', ['user_id', 'target_role', 'performance_score', 'overall_score'], unique=False)
    op.create_index(op.f('idx_sessions_completed_at'), 'interview_sessions', ['completed_at'], unique=False)
    op.create_index(op.f('idx_sessions_active_user_performance'), 'interview_sessions', ['user_id', 'performance_score', 'created_at'], unique=False)
    op.create_index(op.f('idx_interview_sessions_user_status_date'), 'interview_sessions', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('idx_interview_sessions_session_mode'), 'interview_sessions', ['session_mode'], unique=False)
    op.create_index(op.f('idx_interview_sessions_performance_score'), 'interview_sessions', ['performance_score'], unique=False)
    op.create_index(op.f('idx_interview_sessions_parent_session'), 'interview_sessions', ['parent_session_id'], unique=False)
    op.create_index(op.f('idx_interview_sessions_difficulty_level'), 'interview_sessions', ['difficulty_level'], unique=False)
    op.alter_column('interview_sessions', 'session_mode',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('new', 'practice_again', 'continued'),
               existing_nullable=True,
               existing_server_default=sa.text("'new'"))
    op.alter_column('interview_sessions', 'difficulty_level',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('easy', 'medium', 'hard', 'expert'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('interview_sessions', 'performance_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.drop_column('interview_sessions', 'next_difficulty')
    # ### end Alembic commands ###